### ISSUE TITLE
Docker build is broken

### ISSUE THREAD

**Issue by alzix** [ikatson/docker-reviewboard#13]
Error unpacking rpm package httpd-2.4.6-40.el7.centos.4.x86_64

seems to be a known issue: https://github.com/docker/hub-feedback/issues/461

**Comment by ikatson** [comment]
Hmm, strange it works for me. I did ```docker pull centos:7``` to refresh the cache.
Looks like I can't do anything with it until they fix in upstream anyway.

Thanks for the report! If it works for you, you can close it.

**Comment by matclab** [comment]
As a workaround, using centos/httpd as a base image worked for me.

**Comment by ikatson** [comment]
Hi, @alzix @matclab , I added a workaround from https://github.com/docker/hub-feedback/issues/461 into the Dockerfile, and pushed to master, everything works well for me. Let me know if you still see the issue with that fix.

**Comment by matclab** [comment]
Thanks @ikatson.

I tried the workaround on my side, but I can not see the link between the nodoc flags and the cap_set_file problem. It didn't work here.

As said in https://github.com/docker/hub-feedback/issues/461#issuecomment-234952494 the culprit is a bug with AUFS driver on docker side : https://github.com/moby/moby/issues/6980 (still opened).

Thus using centos/httpd works because the image is build on another docker instance which does not use AUFS.

The other workaround is to change your docker device driver, but it may be problematic on a production server.

I guess you can close the ticket as won't fix, because it is on the docker side, not yours.

**Comment by ikatson** [comment]
Thanks @matclab for a clear explanation. I did not pay much attention to the whole thread in docker#461, just looked at the bottom comments. Reverted the commit to master, closing this issue.
